/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBootstrapRouteImport } from './routes/admin/bootstrap'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminVerifiersRouteImport } from './routes/admin/verifiers'
import { Route as ApiCorpusImportRouteImport } from './routes/api/corpus-import'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CompaniesSlugRouteImport } from './routes/companies/$slug'
import { Route as EvidenceIdRouteImport } from './routes/evidence/$id'
import { Route as EvidenceExpiredRouteImport } from './routes/evidence/expired'
import { Route as EvidenceExpiringRouteImport } from './routes/evidence/expiring'
import { Route as SectorsSlugRouteImport } from './routes/sectors/$slug'
import { Route as VerifiersIndexRouteImport } from './routes/verifiers/index'
import { Route as VerifiersSlugRouteImport } from './routes/verifiers/$slug'
import { Route as AdminCompaniesIndexRouteImport } from './routes/admin/companies/index'
import { Route as AdminCompaniesIdRouteImport } from './routes/admin/companies/$id'
import { Route as AdminEvidenceIndexRouteImport } from './routes/admin/evidence/index'
import { Route as AdminEvidenceIdRouteImport } from './routes/admin/evidence/$id'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminJobsIdRouteImport } from './routes/admin/jobs/$id'
import { Route as AdminReviewIndexRouteImport } from './routes/admin/review/index'
import { Route as AdminReviewIdRouteImport } from './routes/admin/review/$id'
import { Route as AdminSourcesIndexRouteImport } from './routes/admin/sources/index'
import { Route as AdminSourcesIdRouteImport } from './routes/admin/sources/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBootstrapRoute = AdminBootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVerifiersRoute = AdminVerifiersRouteImport.update({
  id: '/verifiers',
  path: '/verifiers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiCorpusImportRoute = ApiCorpusImportRouteImport.update({
  id: '/api/corpus-import',
  path: '/api/corpus-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIdRoute = EvidenceIdRouteImport.update({
  id: '/evidence/$id',
  path: '/evidence/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceExpiredRoute = EvidenceExpiredRouteImport.update({
  id: '/evidence/expired',
  path: '/evidence/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceExpiringRoute = EvidenceExpiringRouteImport.update({
  id: '/evidence/expiring',
  path: '/evidence/expiring',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSlugRoute = SectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiersIndexRoute = VerifiersIndexRouteImport.update({
  id: '/verifiers/',
  path: '/verifiers/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiersSlugRoute = VerifiersSlugRouteImport.update({
  id: '/verifiers/$slug',
  path: '/verifiers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCompaniesIdRoute = AdminCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEvidenceIndexRoute = AdminEvidenceIndexRouteImport.update({
  id: '/evidence/',
  path: '/evidence/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEvidenceIdRoute = AdminEvidenceIdRouteImport.update({
  id: '/evidence/$id',
  path: '/evidence/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsIdRoute = AdminJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewIndexRoute = AdminReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewIdRoute = AdminReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSourcesIndexRoute = AdminSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSourcesIdRoute = AdminSourcesIdRouteImport.update({
  id: '/sources/$id',
  path: '/sources/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/corrections': typeof CorrectionsRoute
  '/methodology': typeof MethodologyRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/submit': typeof SubmitRoute
  '/updates': typeof UpdatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/verifiers': typeof AdminVerifiersRoute
  '/api/corpus-import': typeof ApiCorpusImportRoute
  '/api/cron': typeof ApiCronRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/evidence/$id': typeof EvidenceIdRoute
  '/evidence/expired': typeof EvidenceExpiredRoute
  '/evidence/expiring': typeof EvidenceExpiringRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/verifiers/$slug': typeof VerifiersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/verifiers/': typeof VerifiersIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/evidence/$id': typeof AdminEvidenceIdRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
  '/admin/sources/$id': typeof AdminSourcesIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
  '/admin/evidence/': typeof AdminEvidenceIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/review/': typeof AdminReviewIndexRoute
  '/admin/sources/': typeof AdminSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corrections': typeof CorrectionsRoute
  '/methodology': typeof MethodologyRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/submit': typeof SubmitRoute
  '/updates': typeof UpdatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/verifiers': typeof AdminVerifiersRoute
  '/api/corpus-import': typeof ApiCorpusImportRoute
  '/api/cron': typeof ApiCronRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/evidence/$id': typeof EvidenceIdRoute
  '/evidence/expired': typeof EvidenceExpiredRoute
  '/evidence/expiring': typeof EvidenceExpiringRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/verifiers/$slug': typeof VerifiersSlugRoute
  '/admin': typeof AdminIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/verifiers': typeof VerifiersIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/evidence/$id': typeof AdminEvidenceIdRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
  '/admin/sources/$id': typeof AdminSourcesIdRoute
  '/admin/companies': typeof AdminCompaniesIndexRoute
  '/admin/evidence': typeof AdminEvidenceIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/review': typeof AdminReviewIndexRoute
  '/admin/sources': typeof AdminSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/corrections': typeof CorrectionsRoute
  '/methodology': typeof MethodologyRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/submit': typeof SubmitRoute
  '/updates': typeof UpdatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bootstrap': typeof AdminBootstrapRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/verifiers': typeof AdminVerifiersRoute
  '/api/corpus-import': typeof ApiCorpusImportRoute
  '/api/cron': typeof ApiCronRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/evidence/$id': typeof EvidenceIdRoute
  '/evidence/expired': typeof EvidenceExpiredRoute
  '/evidence/expiring': typeof EvidenceExpiringRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/verifiers/$slug': typeof VerifiersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/verifiers/': typeof VerifiersIndexRoute
  '/admin/companies/$id': typeof AdminCompaniesIdRoute
  '/admin/evidence/$id': typeof AdminEvidenceIdRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/review/$id': typeof AdminReviewIdRoute
  '/admin/sources/$id': typeof AdminSourcesIdRoute
  '/admin/companies/': typeof AdminCompaniesIndexRoute
  '/admin/evidence/': typeof AdminEvidenceIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/review/': typeof AdminReviewIndexRoute
  '/admin/sources/': typeof AdminSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/corrections'
    | '/methodology'
    | '/search'
    | '/sources'
    | '/submit'
    | '/updates'
    | '/admin/audit'
    | '/admin/bootstrap'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/verifiers'
    | '/api/corpus-import'
    | '/api/cron'
    | '/companies/$slug'
    | '/evidence/$id'
    | '/evidence/expired'
    | '/evidence/expiring'
    | '/sectors/$slug'
    | '/verifiers/$slug'
    | '/admin/'
    | '/companies/'
    | '/verifiers/'
    | '/admin/companies/$id'
    | '/admin/evidence/$id'
    | '/admin/jobs/$id'
    | '/admin/review/$id'
    | '/admin/sources/$id'
    | '/admin/companies/'
    | '/admin/evidence/'
    | '/admin/jobs/'
    | '/admin/review/'
    | '/admin/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corrections'
    | '/methodology'
    | '/search'
    | '/sources'
    | '/submit'
    | '/updates'
    | '/admin/audit'
    | '/admin/bootstrap'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/verifiers'
    | '/api/corpus-import'
    | '/api/cron'
    | '/companies/$slug'
    | '/evidence/$id'
    | '/evidence/expired'
    | '/evidence/expiring'
    | '/sectors/$slug'
    | '/verifiers/$slug'
    | '/admin'
    | '/companies'
    | '/verifiers'
    | '/admin/companies/$id'
    | '/admin/evidence/$id'
    | '/admin/jobs/$id'
    | '/admin/review/$id'
    | '/admin/sources/$id'
    | '/admin/companies'
    | '/admin/evidence'
    | '/admin/jobs'
    | '/admin/review'
    | '/admin/sources'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/corrections'
    | '/methodology'
    | '/search'
    | '/sources'
    | '/submit'
    | '/updates'
    | '/admin/audit'
    | '/admin/bootstrap'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/verifiers'
    | '/api/corpus-import'
    | '/api/cron'
    | '/companies/$slug'
    | '/evidence/$id'
    | '/evidence/expired'
    | '/evidence/expiring'
    | '/sectors/$slug'
    | '/verifiers/$slug'
    | '/admin/'
    | '/companies/'
    | '/verifiers/'
    | '/admin/companies/$id'
    | '/admin/evidence/$id'
    | '/admin/jobs/$id'
    | '/admin/review/$id'
    | '/admin/sources/$id'
    | '/admin/companies/'
    | '/admin/evidence/'
    | '/admin/jobs/'
    | '/admin/review/'
    | '/admin/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CorrectionsRoute: typeof CorrectionsRoute
  MethodologyRoute: typeof MethodologyRoute
  SearchRoute: typeof SearchRoute
  SourcesRoute: typeof SourcesRoute
  SubmitRoute: typeof SubmitRoute
  UpdatesRoute: typeof UpdatesRoute
  ApiCorpusImportRoute: typeof ApiCorpusImportRoute
  ApiCronRoute: typeof ApiCronRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  EvidenceIdRoute: typeof EvidenceIdRoute
  EvidenceExpiredRoute: typeof EvidenceExpiredRoute
  EvidenceExpiringRoute: typeof EvidenceExpiringRoute
  SectorsSlugRoute: typeof SectorsSlugRoute
  VerifiersSlugRoute: typeof VerifiersSlugRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  VerifiersIndexRoute: typeof VerifiersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bootstrap': {
      id: '/admin/bootstrap'
      path: '/bootstrap'
      fullPath: '/admin/bootstrap'
      preLoaderRoute: typeof AdminBootstrapRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/verifiers': {
      id: '/admin/verifiers'
      path: '/verifiers'
      fullPath: '/admin/verifiers'
      preLoaderRoute: typeof AdminVerifiersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/corpus-import': {
      id: '/api/corpus-import'
      path: '/api/corpus-import'
      fullPath: '/api/corpus-import'
      preLoaderRoute: typeof ApiCorpusImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/$id': {
      id: '/evidence/$id'
      path: '/evidence/$id'
      fullPath: '/evidence/$id'
      preLoaderRoute: typeof EvidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/expired': {
      id: '/evidence/expired'
      path: '/evidence/expired'
      fullPath: '/evidence/expired'
      preLoaderRoute: typeof EvidenceExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/expiring': {
      id: '/evidence/expiring'
      path: '/evidence/expiring'
      fullPath: '/evidence/expiring'
      preLoaderRoute: typeof EvidenceExpiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$slug': {
      id: '/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof SectorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifiers/': {
      id: '/verifiers/'
      path: '/verifiers'
      fullPath: '/verifiers/'
      preLoaderRoute: typeof VerifiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifiers/$slug': {
      id: '/verifiers/$slug'
      path: '/verifiers/$slug'
      fullPath: '/verifiers/$slug'
      preLoaderRoute: typeof VerifiersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies/': {
      id: '/admin/companies/'
      path: '/companies'
      fullPath: '/admin/companies/'
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/companies/$id': {
      id: '/admin/companies/$id'
      path: '/companies/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AdminCompaniesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/evidence/': {
      id: '/admin/evidence/'
      path: '/evidence'
      fullPath: '/admin/evidence/'
      preLoaderRoute: typeof AdminEvidenceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/evidence/$id': {
      id: '/admin/evidence/$id'
      path: '/evidence/$id'
      fullPath: '/admin/evidence/$id'
      preLoaderRoute: typeof AdminEvidenceIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/$id': {
      id: '/admin/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AdminJobsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/review/': {
      id: '/admin/review/'
      path: '/review'
      fullPath: '/admin/review/'
      preLoaderRoute: typeof AdminReviewIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/review/$id': {
      id: '/admin/review/$id'
      path: '/review/$id'
      fullPath: '/admin/review/$id'
      preLoaderRoute: typeof AdminReviewIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sources/': {
      id: '/admin/sources/'
      path: '/sources'
      fullPath: '/admin/sources/'
      preLoaderRoute: typeof AdminSourcesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sources/$id': {
      id: '/admin/sources/$id'
      path: '/sources/$id'
      fullPath: '/admin/sources/$id'
      preLoaderRoute: typeof AdminSourcesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBootstrapRoute: typeof AdminBootstrapRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminVerifiersRoute: typeof AdminVerifiersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCompaniesIdRoute: typeof AdminCompaniesIdRoute
  AdminEvidenceIdRoute: typeof AdminEvidenceIdRoute
  AdminJobsIdRoute: typeof AdminJobsIdRoute
  AdminReviewIdRoute: typeof AdminReviewIdRoute
  AdminSourcesIdRoute: typeof AdminSourcesIdRoute
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
  AdminEvidenceIndexRoute: typeof AdminEvidenceIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminReviewIndexRoute: typeof AdminReviewIndexRoute
  AdminSourcesIndexRoute: typeof AdminSourcesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBootstrapRoute: AdminBootstrapRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminVerifiersRoute: AdminVerifiersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCompaniesIdRoute: AdminCompaniesIdRoute,
  AdminEvidenceIdRoute: AdminEvidenceIdRoute,
  AdminJobsIdRoute: AdminJobsIdRoute,
  AdminReviewIdRoute: AdminReviewIdRoute,
  AdminSourcesIdRoute: AdminSourcesIdRoute,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
  AdminEvidenceIndexRoute: AdminEvidenceIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminReviewIndexRoute: AdminReviewIndexRoute,
  AdminSourcesIndexRoute: AdminSourcesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CorrectionsRoute: CorrectionsRoute,
  MethodologyRoute: MethodologyRoute,
  SearchRoute: SearchRoute,
  SourcesRoute: SourcesRoute,
  SubmitRoute: SubmitRoute,
  UpdatesRoute: UpdatesRoute,
  ApiCorpusImportRoute: ApiCorpusImportRoute,
  ApiCronRoute: ApiCronRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  EvidenceIdRoute: EvidenceIdRoute,
  EvidenceExpiredRoute: EvidenceExpiredRoute,
  EvidenceExpiringRoute: EvidenceExpiringRoute,
  SectorsSlugRoute: SectorsSlugRoute,
  VerifiersSlugRoute: VerifiersSlugRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  VerifiersIndexRoute: VerifiersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
